import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomCursor from "@/app/_components/layout/CustomCursor";
import Header from "@/app/_components/layout/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mahsa Geramy Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
  return (
      <html
          lang="en"
          className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
      <body className="min-h-full flex flex-col bg-zinc-50 justify-center items-center dark:bg-black pb-10">
      <CustomCursor/>
      <Header/>
      {children}
      </body>
      </html>
  );
}
